import keyboard
from main import playerY, playerX
def forv():
    global playerX
    playerX -=1
def back():
    global playerX
    playerX +=1
def rig():
    global playerY
    playerY -=1
def lef():
    global playerY
    playerY +=1
def setup():
    keyboard.add_hotkey("a", rig)
    keyboard.add_hotkey("d", lef)
    keyboard.add_hotkey("w", forv)
    keyboard.add_hotkey("s", back)